// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdsttyasbmrpnvctbnju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkc3R0eWFzYm1ycG52Y3Ribmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDgyOTcsImV4cCI6MjA2NDYyNDI5N30.-w0gxkcAFvEmTPyfn1vJjLHed8vrCLdas9RGLG0q8Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);